using System;
using System.Collections.Generic;

namespace TabbyStudios
{
    public class ComponentMap : FastCacheSearch
    {
        public static Dictionary<string, List<Func<VisualComponent>>> components = new()
        {
            { "AlwaysShowSearchBar-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "AreYouSureLabel-", new List<Func<VisualComponent>> { () => new AreYouSureLabel() } },
            { "AutoDeleteMenuItems-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "CancelButton-", new List<Func<VisualComponent>> { () => new CancelButton() } },
            { "CloseMenusOnAltTab-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "ConfirmButton-", new List<Func<VisualComponent>> { () => new ConfirmButton() } },
            { "CurrentProfileDropdown-", new List<Func<VisualComponent>> { () => new CurrentProfileDropdown() } },
            { "CustomMenu-CustomMenuLayout", new List<Func<VisualComponent>> { () => new CustomMenuLayout() } },
            { "DefaultMenuDropdown-StringSetting", new List<Func<VisualComponent>> { () => new StringSetting() } },
            { "Delete-DeleteItemButton-IconButton", new List<Func<VisualComponent>> { () => new DeleteItemButton(), () => new IconButton() } },
            { "DeleteProfileButton-", new List<Func<VisualComponent>> { () => new DeleteProfileButton() } },
            { "DocumentationFooterButton-DocumentationButton", new List<Func<VisualComponent>> { () => new DocumentationButton() } },
            { "DropdownField-ValueChanger", new List<Func<VisualComponent>> { () => new ValueChanger() } },
            { "DuplicateProfileButton-", new List<Func<VisualComponent>> { () => new DuplicateProfileButton() } },
            { "EmptySpace-", new List<Func<VisualComponent>> { () => new EmptySpace() } },
            { "ExpandTopLevelMenus-BoolSetting-ValueChanger", new List<Func<VisualComponent>> { () => new BoolSetting(), () => new ValueChanger() } },
            { "ExportProfileButton-", new List<Func<VisualComponent>> { () => new ExportProfileButton() } },
            { "ExportSettingsButton-", new List<Func<VisualComponent>> { () => new ExportSettingsButton() } },
            { "FallbackInputHandlingToggle-", new List<Func<VisualComponent>> { () => new FallbackInputHandlingToggle() } },
            { "FeatureList-", new List<Func<VisualComponent>> { () => new FeatureList() } },
            { "FixList-", new List<Func<VisualComponent>> { () => new FixList() } },
            { "FooterContactButton-DiscordButton", new List<Func<VisualComponent>> { () => new DiscordButton() } },
            { "FooterSupportButton-DiscordButton", new List<Func<VisualComponent>> { () => new DiscordButton() } },
            { "GetStartedButton-DocumentationButton", new List<Func<VisualComponent>> { () => new DocumentationButton() } },
            { "HasChildrenToggle-", new List<Func<VisualComponent>> { () => new HasChildrenToggle() } },
            { "HideDisabledItems-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "HoldKeyToReorder-BoolSetting-ValueChanger", new List<Func<VisualComponent>> { () => new BoolSetting(), () => new ValueChanger() } },
            { "ImportExamplesButton-", new List<Func<VisualComponent>> { () => new ImportExamplesButton() } },
            { "ImportProfileButton-", new List<Func<VisualComponent>> { () => new ImportProfileButton() } },
            { "ImportSettingsButton-", new List<Func<VisualComponent>> { () => new ImportSettingsButton() } },
            { "ImprovementList-", new List<Func<VisualComponent>> { () => new ImprovementList() } },
            { "InputField-ValueChanger", new List<Func<VisualComponent>> { () => new ValueChanger() } },
            { "JoinDiscord-DiscordButton", new List<Func<VisualComponent>> { () => new DiscordButton() } },
            { "LockButton-BoolSetting-ValueChanger", new List<Func<VisualComponent>> { () => new BoolSetting(), () => new ValueChanger() } },
            { "MaxItemHeight-IntSetting", new List<Func<VisualComponent>> { () => new IntSetting() } },
            { "MaxItemsPerMenu-IntSetting", new List<Func<VisualComponent>> { () => new IntSetting() } },
            { "MaxMenuHeight-IntSetting", new List<Func<VisualComponent>> { () => new IntSetting() } },
            { "MaxMenuWidth-IntSetting", new List<Func<VisualComponent>> { () => new IntSetting() } },
            { "MenuCustomizationContainer-", new List<Func<VisualComponent>> { () => new MenuCustomizationContainer() } },
            { "MenuFadein-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "MenuFontSize-IntSetting", new List<Func<VisualComponent>> { () => new IntSetting() } },
            { "MenuOpenDelay-IntSetting", new List<Func<VisualComponent>> { () => new IntSetting() } },
            { "MenuScale-IntSetting", new List<Func<VisualComponent>> { () => new IntSetting() } },
            { "MenusTabContent-", new List<Func<VisualComponent>> { () => new MenusTabContent() } },
            { "MenusTab-TabButton", new List<Func<VisualComponent>> { () => new TabButton() } },
            { "MenuToolbarButton-", new List<Func<VisualComponent>> { () => new MenuToolbarButton() } },
            { "MenuToolbarContainer-", new List<Func<VisualComponent>> { () => new MenuToolbarContainer() } },
            { "MoreByTabbyStudiosButton-", new List<Func<VisualComponent>> { () => new MoreByTabbyStudiosButton() } },
            { "Name-TextComponent", new List<Func<VisualComponent>> { () => new TextComponent() } },
            { "NewItem-NewItemButton-IconButton", new List<Func<VisualComponent>> { () => new NewItemButton(), () => new IconButton() } },
            { "NewProfileButton-", new List<Func<VisualComponent>> { () => new NewProfileButton() } },
            { "NewSeparator-NewSeparatorButton-IconButton", new List<Func<VisualComponent>> { () => new NewSeparatorButton(), () => new IconButton() } },
            { "PopupRoot-", new List<Func<VisualComponent>> { () => new PopupRoot() } },
            { "PreferencesTabContent-", new List<Func<VisualComponent>> { () => new PreferencesTabContent() } },
            { "PreferencesTab-TabButton", new List<Func<VisualComponent>> { () => new TabButton() } },
            { "PreviewButton-BoolSetting-ValueChanger", new List<Func<VisualComponent>> { () => new BoolSetting(), () => new ValueChanger() } },
            { "ProfileButtons-", new List<Func<VisualComponent>> { () => new ProfileButtons() } },
            { "RebuildDefaultProfileButton-", new List<Func<VisualComponent>> { () => new RebuildDefaultProfileButton() } },
            { "RenameProfileButton-", new List<Func<VisualComponent>> { () => new RenameProfileButton() } },
            { "ResetToDefaultButton-", new List<Func<VisualComponent>> { () => new ResetToDefaultButton() } },
            { "RoundedMenuCorners-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "SearchBar-", new List<Func<VisualComponent>> { () => new SearchBar() } },
            { "SearchEverywhere-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "SettingsMenuZoom-SliderSetting-ValueChanger", new List<Func<VisualComponent>> { () => new SliderSetting(), () => new ValueChanger() } },
            { "Shortcut-TextComponent", new List<Func<VisualComponent>> { () => new TextComponent() } },
            { "ShowMenuToolbarContainer-", new List<Func<VisualComponent>> { () => new ShowMenuToolbarContainer() } },
            { "ShowWhenDropdown-", new List<Func<VisualComponent>> { () => new ShowWhenDropdown() } },
            { "Switch-SwitchVisibilityButton-IconButton", new List<Func<VisualComponent>> { () => new SwitchVisibilityButton(), () => new IconButton() } },
            { "TabbyScrollView-", new List<Func<VisualComponent>> { () => new TabbyScrollView() } },
            { "TabContentContainer-", new List<Func<VisualComponent>> { () => new TabContentContainer() } },
            { "TabGroup-", new List<Func<VisualComponent>> { () => new TabGroup() } },
            { "Toggle-ValueChanger", new List<Func<VisualComponent>> { () => new ValueChanger() } },
            { "UseAnonymousMenus-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "UseCustomMenus-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "UseGradientToggle-", new List<Func<VisualComponent>> { () => new UseGradientToggle() } },
            { "UseIcons-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "UseSearchBar-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "UseSearchBarOnSubmenus-BoolSetting", new List<Func<VisualComponent>> { () => new BoolSetting() } },
            { "VersionLabel-", new List<Func<VisualComponent>> { () => new VersionLabel() } },
            { "ViewChangelogButton-", new List<Func<VisualComponent>> { () => new ViewChangelogButton() } },
            { "WelcomeTabContent-", new List<Func<VisualComponent>> { () => new WelcomeTabContent() } },
            { "WelcomeTab-TabButton", new List<Func<VisualComponent>> { () => new TabButton() } },
            { "WhatsNewInLabel-", new List<Func<VisualComponent>> { () => new WhatsNewInLabel() } }
        };
    }
}
